# ./docker-compose.yml

version: '3'

services:
  client:
      build:
        context: ./consumer_client
        dockerfile: Dockerfile
      ports:
        - 4000:4000
      command: npm run dev
      volumes:
      - ./consumer_client:/consumer_client/
      - /consumer_client/node_modules
      - /consumer_client/.next
      stdin_open: true
      tty: true

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: dev
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_HOST: '%'
    ports:
      - "9906:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d/:ro

  web:
    image: php:8.0-apache
    container_name: php_web
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
